server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: react-admin-server
  datasource:
    url: jdbc:mysql://121.40.242.207:3306/test?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: starTrails@2023
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0